import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin } from 'react-icons/ai';
import deved from '../public/AliCThumb.png';
import design from '../public/design.png';
import consulting from '../public/WayneGain.png';
import glove from '../public/boxing_gloves.png';
import PunchIn from '../public/PunchIn.png';
import DataTreeLogo from '../public/DataTreeLogo.png';
import DataTree from '../public/DataTree.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : 'bg-beige-100'}>
      <Head>
        <title>Ali Chowdhury Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-beige-100 px-10 md:px-20 lg:px-40 dark:bg-gray-500">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl" font-burtons>
              developed by Ali
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1sSTBkwDNel-p406f2K1wb7ACPkguxmbF/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
              <li></li>
            </ul>
          </nav>
          <div
            className={`text-center py-10 px-6 rounded-lg shadow-md ${
              darkMode
                ? 'bg-gray-800 text-gray-200'
                : 'bg-gradient-to-r from-teal-100 to-teal-300 text-gray-800'
            }`}
          >
            <h2
              className={`text-4xl font-semibold ${
                darkMode ? 'text-teal-400' : 'text-teal-600'
              } md:text-5xl`}
            >
              Ali Chowdhury
            </h2>
            <h3
              className={`text-xl py-4 ${
                darkMode ? 'text-gray-300' : 'md:text-2xl'
              }`}
            >
              Future Wayne State University Graduate
            </h3>
            <p
              className={`text-md py-2 leading-7 ${
                darkMode ? 'text-gray-400' : 'text-gray-800'
              } md:text-lg max-w-xl mx-auto`}
            >
              Using my experience in both the workforce and in my degree, I&apos;m
              currently looking for an internship/career to be able to prove my
              value and worth as it pertains to your company.
            </p>
          </div>


          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>

  <a href="https://www.linkedin.com/in/ali-chowdhury-786125175/" target="_blank" rel="noopener noreferrer">
    <AiFillLinkedin/>
  </a>
</div>
<div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
  <Image src ={deved} layout='fill' objectFit='cover'/>
</div>

        </section>
        <section >
          <div className='text-center bg-amber-300 dark:bg-slate-500 p-6 rounded-lg shadow-md'>
            <h3 className='text-5xl py-1 font-bold '>
              About me
            </h3>
            <p className='text-md py-2 leading-8 text-gray-800 text-2xl'>I am a Wayne State student in my final year of computer science.
            I have both a background in both programming and in IT to help suit your needs. I have come to know various programming languages and methods to use them.
            I am proficient in 
            <span className="text-teal-400"> UX design, C++, Python, </span> and <span className="text-teal-400">Docker</span> and I look forward to expanding my skillset with you.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>My main priority is to secure an environment where I can continually
            <span className="text-teal-500"> learn and improve</span>, both in the work environment and out.
            </p>
          </div>
          <div className='lg:flex justify-center gap-10'>
            {/*First card*/}
          <div className='text-center shadow-lg p-6 rounded-xl my-10 bg-teal-500 dark:bg-gray-800 dark:shadow-lg flex flex-col items-center'>
          <Image src={design} width={100} height={100} />
          <h3 className='text-lg font-medium pt-6 pb-2 text-white'>Tools Under My Belt</h3>
          <h4 className='py-4 dark:text-teal-600 '>Programs/Languages I have Proficiency In</h4>
          <p className='text-white font-bold py-1'>Photoshop</p>
          <p className='text-white font-bold py-1'>DaVinci Resolve/Premiere</p>
          <p className='text-white font-bold py-1'>Python</p>
          <p className='text-white font-bold py-1'>Docker</p>
          </div>
          {/*Second card*/}
          <div className='text-center shadow-lg p-6 rounded-xl my-10 bg-teal-500 dark:bg-gray-800 dark:shadow-lg flex flex-col items-center'>
          <Image src={consulting} width={100} height={100}/>
          <h3 className='text-lg font-medium pt-6 pb-2 text-white'>Project: Microservice-based Fitness Tracker</h3>
          <h4 className='py-4 dark:text-teal-600 '>Tools used:</h4>
          <p className='text-white font-bold py-1'>HTML/CSS/JavaScript</p>
          <p className='text-white font-bold py-1'>Flask RESTful APIs</p>
          <p className='text-white font-bold py-1'>Docker</p>
          <p className='text-white font-bold py-1'>Python</p>
          <a href='https://github.com/AliChowdhuryA/WayneGain' target='_blank' rel='noopener noreferrer' className='mt-4 inline-block bg-gray-800 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition duration-300 ease-in-out'>
            View on GitHub
          </a>
          </div>

            {/*Third card*/}
            <div className='text-center shadow-lg p-6 rounded-xl my-10 bg-teal-500 dark:bg-gray-800 dark:shadow-lg flex flex-col items-center'>
          <Image src={glove} width={100} height={100}/>
          <h3 className='text-lg font-medium pt-6 pb-2 text-white'>Project: Boxing Game</h3>
          <h4 className='py-4 dark:text-teal-600 '>Tools used:</h4>
          <p className='text-white font-bold py-1'>Python/PyGame</p>
          <p className='text-white font-bold py-1'>Repl</p>

          <a href='https://replit.com/@AliChowdhury/PunchOut' target='_blank' rel='noopener noreferrer' className='mt-4 inline-block bg-gray-800 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition duration-300 ease-in-out'>
            View on Repl
          </a>
          </div>
                      {/*Fourth card*/}
                      <div className='text-center shadow-lg p-6 rounded-xl my-10 bg-teal-500 dark:bg-gray-800 dark:shadow-lg flex flex-col items-center'>
          <Image src={DataTreeLogo} width={100} height={100}/>
          <h3 className='text-lg font-medium pt-6 pb-2 text-white'>Project: DataTree</h3>
          <h4 className='py-4 dark:text-teal-600 '>Tools used:</h4>
          <p className='text-white font-bold py-1'>Python</p>
          <p className='text-white font-bold py-1'>Custom/Tkinter</p>
          <p className='text-white font-bold py-1'>Bootstrap</p>

          <a href='https://github.com/CSC4110-Group1/CSC4110-Project-2/' target='_blank' rel='noopener noreferrer' className='mt-4 inline-block bg-gray-800 text-white px-4 py-2 rounded-md hover:bg-gray-700 transition duration-300 ease-in-out'>
            View on Repl
          </a>
          </div>
          </div>
        </section>
        <section className='bg-beige-100 dark:bg-gray-500'>

          {/*Portfolio portion */}
        <div className={`bg-teal-100 dark:bg-gray-700 p-6 rounded-lg shadow-md text-center ${darkMode ? 'dark:text-white' : 'dark:text-gray-800'}`}>
  <h3 className={`text-3xl font-semibold mb-2 ${darkMode ? 'text-gray-300' : 'text-gray-800'}`}>
    Portfolio
  </h3>

  <p className={`text-md py-2 leading-7 max-w-md mx-auto ${darkMode ? 'text-gray-300' : 'text-gray-800'}`}>
    This portfolio was created using {" "}
    <span className="text-teal-500 font-bold">TailWindCSS</span> and <span className="text-teal-500 font-bold">React</span>.
  </p>
  <a
    href='https://github.com/AliChowdhuryA/FCCReactPortfolio'
    target='_blank'
    rel='noopener noreferrer'
    className={`mt-4 inline-block bg-teal-500 dark:bg-gray-800 text-white px-4 py-2 rounded-md hover:bg-teal-600 dark:hover:bg-gray-700 transition duration-300 ease-in-out ${darkMode ? 'dark:text-gray-300' : 'dark:text-white'}`}
  >
    Check out the repository
  </a>
</div>




          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
            <Image src={PunchIn} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
            <Image src={DataTree} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
                                   
          </div>
        </section>
      </main>

    </div>
  )
}
